# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rikir/Documents/FPGA_projects/Sampler_XADC/Sampler_XADC.srcs/sources_1/ip/fifo_generator_uart/fifo_generator_uart.xci
# IP: The module: 'fifo_generator_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rikir/Documents/FPGA_projects/Sampler_XADC/Sampler_XADC.gen/sources_1/ip/fifo_generator_uart/fifo_generator_uart.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_uart'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rikir/Documents/FPGA_projects/Sampler_XADC/Sampler_XADC.gen/sources_1/ip/fifo_generator_uart/fifo_generator_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/rikir/Documents/FPGA_projects/Sampler_XADC/Sampler_XADC.srcs/sources_1/ip/fifo_generator_uart/fifo_generator_uart.xci
# IP: The module: 'fifo_generator_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rikir/Documents/FPGA_projects/Sampler_XADC/Sampler_XADC.gen/sources_1/ip/fifo_generator_uart/fifo_generator_uart.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/rikir/Documents/FPGA_projects/Sampler_XADC/Sampler_XADC.gen/sources_1/ip/fifo_generator_uart/fifo_generator_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
